### ISSUE TITLE
feature request: ability to pass path to config file

### ISSUE THREAD

**Issue by mrsauravsahu** [xojs/xo#638] opened 2021-11-20 21:05 UTC
To reuse xo-config across multiple projects in my monorepo, I have to run xo from each of my projects directory (otherwise I get file is not in cwd error)

```bash
$ ./node_modules/.bin/xo ../../srv/souvenirs
Error: Path /souvenirs/srv/souvenirs/BUILD is not in cwd /souvenirs/common/lint_xo
    at ensureAbsolutePathForCwd (file:///souvenirs/common/lint_xo/node_modules/globby/gitignore.js:54:9)
    at file:///souvenirs/common/lint_xo/node_modules/globby/gitignore.js:60:95
    at file:///souvenirs/common/lint_xo/node_modules/globby/index.js:142:47
    at Array.filter (<anonymous>)
    at globby (file:///souvenirs/common/lint_xo/node_modules/globby/index.js:142:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async globFiles (file:///souvenirs/common/lint_xo/node_modules/xo/index.js:23:16)
    at async Object.lintFiles (file:///souvenirs/common/lint_xo/node_modules/xo/index.js:67:16)
    at async file:///souvenirs/common/lint_xo/node_modules/xo/cli.js:211:18
```

As mentioned in the docs, the xo config can be put in the package.json, with the `xo` key. This, again, doesn't work because of the above error, as I will be running xo from the projects' folder and each of them have their own package.json and I want to keep the xo-config centralized.

Is it already possible to pass the path to config as a switch? If not, I'm happy to collaborate and add this feature in!

Thanks
-S

**Comment by macarie** [comment] 2021-11-30 22:36
I (think?) have the same problem.

In a monorepo setup, I have xo as a dev-dependency and its configuration inside `/package.json,` then I have `/packages/module/package.json` containing a `lint` script (`"xo"`).

Xo doesn't pick up the configuration from `/package.json` if launched from inside the module's directory, and neither does it if launched from the root directory with `pnpm run -r lint`.

The workaround I found to be working is having `"xo --cwd ../.. packages/module/source"` as my `lint` script in `/packages/module/package.json`.

I've looked a bit around, and I think the line that causes this issue is this one: https://github.com/xojs/xo/blob/d3dd11930fbafcb818fdb4c2b37904b2ddba888c/lib/options-manager.js#L103

I've tried locally, and removing the `stopDir` property seems to be solving this issue.

I can open a PR, but I'm not sure if this is indeed a bug or a known/wanted behavior.

**Comment by 8ctopus** [comment] 2022-01-25 04:02
Same problem here. running xo with `--cwd` does not trigger the error but does not lint either.

**Comment by mrsauravsahu** [comment] 2022-03-26 04:40
I'm having to use eslint for now until I add this feature into xo. Would love to work on this together if anyone's interested.

**Comment by AbdallahAbis** [comment] 2022-04-28 01:18
Any workaround for this?

**Comment by mrsauravsahu** [comment] 2022-05-11 21:50
I've made the basic changes in code and everything seems to be working. I didn't have time to look at the test setup. Will do that now.

#664 created a draft PR.

You can pass the config file path like so. 

I'm testing with a playground folder, that's where my code is and config has the .xo-config.json
`./node_modules/.bin/xo --config-path config/.xo-config.json --cwd playground`

**Comment by jwr12135** [comment] 2022-05-12 01:38
The `--config-path` option is a good idea, but It seems like xo should also be able to automatically look up through the file tree for a config so the path does not need to be specified each time.

**Comment by mrsauravsahu** [comment] 2022-05-12 06:29
It does. But for our use case the config isn’t up the file tree. It’s in a different config folder altogether.

**Comment by jwr12135** [comment] 2022-05-12 13:07
It seems like the config resolver is not working for me, I might just open a separate issue.

**Comment by fregante** [comment] 2022-08-06 14:14
Duplicate of https://github.com/xojs/xo/issues/448

**Closed by fregante** 2022-08-06 14:14 UTC
