### ISSUE TITLE
Top level await causes parsing error

### ISSUE THREAD

**Issue by FunctionDJ** [xojs/xo#531] opened 2021-04-13 16:29 UTC
At least Node LTS (14.16) supports top level await.

Why is it causing a parsing error?

![image](https://user-images.githubusercontent.com/34871211/114587724-385b7280-9c86-11eb-986a-de40c90bdaa5.png)

**Comment by sindresorhus** [comment] 2021-04-13 16:55
Duplicate of #525

**Closed by sindresorhus** 2021-04-13 16:55 UTC
