### ISSUE TITLE
Error: Failed to load plugin 'unicorn' declared in 'BaseConfig » /home/yoursunny/xobug/node_modules/xo/config/plugins.js': Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by yoursunny** [xojs/xo#519] opened 2021-02-17 02:22 UTC
## Snippet to Reproduce

**package.json**

```json
{
  "private": true,
  "dependencies": {
    "xo": "^0.37.1"
  }
}
```

**1.js**

```js
console.log("OK");
```

## Actual Behavior

```shell
$ ./node_modules/.bin/xo 1.js
Error: Failed to load plugin 'unicorn' declared in 'BaseConfig » /home/yoursunny/xobug/node_modules/xo/config/plugins.js': Cannot find module '@babel/core'
Require stack:
- /home/yoursunny/xobug/node_modules/@babel/eslint-parser/lib/index.js
- /home/yoursunny/xobug/node_modules/eslint-template-visitor/lib/index.js
- /home/yoursunny/xobug/node_modules/eslint-template-visitor/index.js
- /home/yoursunny/xobug/node_modules/eslint-plugin-unicorn/rules/import-style.js
- /home/yoursunny/xobug/node_modules/import-modules/index.js
- /home/yoursunny/xobug/node_modules/eslint-plugin-unicorn/index.js
- /home/yoursunny/xobug/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /home/yoursunny/xobug/node_modules/@eslint/eslintrc/lib/index.js
- /home/yoursunny/xobug/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/yoursunny/xobug/node_modules/eslint/lib/cli-engine/index.js
- /home/yoursunny/xobug/node_modules/eslint/lib/api.js
- /home/yoursunny/xobug/node_modules/xo/index.js
- /home/yoursunny/xobug/node_modules/xo/cli-main.js
- /home/yoursunny/xobug/node_modules/xo/cli.js
Referenced from: /home/yoursunny/xobug/node_modules/xo/config/plugins.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/yoursunny/xobug/node_modules/@babel/eslint-parser/lib/index.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

## Expected Behavior

No error.

**Comment by sindresorhus** [comment] 2021-02-17 03:47
What Node.js and npm version?

**Comment by yoursunny** [comment] 2021-02-17 06:49
```shell
$ node --version
v14.15.4

$ npm --version
6.14.10

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

**Comment by sindresorhus** [comment] 2021-02-17 08:20
Try upgrading to the latest npm version (v7) and then run: `npm cache clean -fg && rm -rf ./node_modules && npm i`

**Comment by yoursunny** [comment] 2021-02-17 09:09
This issue does not occur with NPM 7.5.4.
Thus, I'd recommend adding an `engine.npm = ^7.5.0` restriction in `package.json`.

This issue still occurs with [PNPM](https://pnpm.js.org) 5.17.2, even with NPM 7 installed.
It used to work with `pnpm install --shamefully-hoist` but suddenly stopped working this week.
Any idea why this may happen?

**Comment by fregante** [comment] 2022-08-06 12:13
Duplicate of https://github.com/xojs/xo/issues/546

**Closed by fregante** 2022-08-06 12:13 UTC
