### ISSUE TITLE
Put xo in pretest when init-ing

### ISSUE THREAD

**Issue by Qix-** [xojs/xo#231] opened 2017-06-12 22:39 UTC
I use XO for everything at this point, and I have been putting it as my `pretest` step instead of `test` with great success:

- It runs before any tests, without me needing to worry about `&&` and lengthy command lines
- I can run `npm run pretest` by itself just to check linting/syntax
- It's cleaner and clearer IMO
- It's functionally backwards compatible

I really think we should start putting it in `pretest` as opposed to `test`.

I know we discussed this in private a long time ago but I'm still advocating it now and just realized `xo --init` is still doing it; figured I'd open an issue to prompt discussion.

**Comment by sindresorhus** [comment] 2017-06-12 22:53
Relevant issue: https://github.com/sindresorhus/xo-init/issues/3

**Comment by Qix-** [comment] 2017-06-12 22:59
I also don't have `xo` installed globally (I try not to). I also don't like the `PATH` hack, either.

**Comment by Qix-** [comment] 2017-06-12 23:32
Also, there's nothing stopping you from doing `xo && ava` of course - and if that's the simplicity of your tests then great.

However, I feel the _correct_ thing is still `pretest`. It checks that the source code is correct and up to standards before tests are even run.

If @npm would be less stingy about breaking features (what is semver for, anyway?) and accepted npm/npm#6943 then this wouldn't be an issue at all.

**Comment by fregante** [comment] 2022-08-06 11:35
Duplicate of https://github.com/xojs/create-xo/issues/3

**Closed by fregante** 2022-08-06 11:35 UTC
