### ISSUE TITLE
Enable eslint `no-shadow` option by default

### ISSUE THREAD

**Issue by zanona** [xojs/xo#280] opened 2018-01-07 01:56 UTC
Hey guys,
Just a suggestion to enable to [no-shadow](https://eslint.org/docs/rules/no-shadow) eslint rule on xo by default as you can see, the below can be really tricky once you have `const path = require('path')` at the head of the file.

https://github.com/sindresorhus/xo/blob/fd89175682810fe2a4ec8d10c3f3104d31ed37f1/lib/options-manager.js#L226-L233

**Comment by pvdlg** [comment] 2018-05-22 15:15
Duplicate of https://github.com/xojs/eslint-config-xo/issues/46

**Closed by pvdlg** 2018-05-22 15:15 UTC
